version: '3.3'
services:
  worker:
    build: ./worker/
    container_name: worker
    environment:
      - WEBSITE_URL=https://aeon.co/essays/on-nonconformism-or-why-we-need-to-be-seen-and-not-herded
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/

